#!/usr/bin/env bash
===================================fine tuning proc predictor++++++++++++++++++++++++++
# rel1_shaw_heuristic_search + selection position
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_shaw_heuristic_search_selection --load_from rel1_shaw_heuristic_search --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 1 0 0 --pos_pred_type 9 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --pos_valid_use pred --pos_train_use oracle --pos_enc_all --print_out --old --fine_tune_dict position_learner final_pos_predictor --pos_attn_type shaw"

# rel1_shaw_heuristic_search + gumbel selection position
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_shaw_heuristic_search_gumbel_selection --load_from rel1_shaw_heuristic_search --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_gumbel_out --pos_n_layers 2 --pos_predict_layer 1 0 0 --pos_pred_type 9 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --pos_valid_use pred --pos_train_use oracle --pos_enc_all --print_out --old --fine_tune_dict position_learner final_pos_predictor --pos_attn_type shaw --pos_analysis"

# rel1_shaw_heuristic_search + indigo position
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_shaw_heuristic_search_indigo --load_from rel1_shaw_heuristic_search --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 1 0 0 --pos_pred_type 8 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --pos_valid_use pred --pos_train_use oracle --pos_enc_all --print_out --old --fine_tune_dict position_learner final_pos_predictor --pos_attn_type shaw"

# rel1_shaw_selection_judge
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_shaw_selection_judge --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 1 0 0 --pos_pred_type 9 --pos_index_out --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_init --keep_grad_for_pos_pred --keep_grad_for_pos_match --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --pos_valid_use pred --pos_train_use oracle --print_out --pos_attn_type shaw --rel_pos_judge"

# rel1_shaw_selection_heuristic_search
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_shaw_selection_heuristic_search --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 1 0 0 --pos_pred_type 9 --pos_index_out --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_init --keep_grad_for_pos_pred --keep_grad_for_pos_match --content_scale 0.5 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --pos_valid_use pred --pos_train_use pred --print_out --pos_attn_type shaw"

# rel1_batch_heuristic_search + ConstrainREL position
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_batch_heuristic_search_ConstrainREL --load_from rel1_batch_heuristic_search --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 1 0 0 --pos_pred_type 11 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --pos_valid_use pred --pos_train_use oracle --pos_enc_all --print_out --old --fine_tune_dict position_learner final_pos_predictor"

# rel1_batch_heuristic_search + ConstrainREL position + Init
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_batch_heuristic_search_ConstrainREL_Init --load_from rel1_batch_heuristic_search --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 1 0 0 --pos_pred_type 11 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --pos_valid_use pred --pos_train_use oracle --pos_enc_all --print_out --old --fine_tune_dict position_learner final_pos_predictor --pos_init"

# rel1_batch_heuristic_search + ConstrainREL position + deeper4
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_batch_heuristic_search_ConstrainREL_P4 --load_from rel1_batch_heuristic_search --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 4 --pos_predict_layer 1 0 0 --pos_pred_type 11 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --pos_valid_use pred --pos_train_use oracle --pos_enc_all --print_out --old --fine_tune_dict position_learner final_pos_predictor"

# rel1_batch_heuristic_search + ConstrainREL position + wider4
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_batch_heuristic_search_ConstrainREL_W4 --load_from rel1_batch_heuristic_search --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_class 4 --pos_n_layers 2 --pos_predict_layer 1 0 0 --pos_pred_type 11 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --pos_valid_use pred --pos_train_use oracle --pos_enc_all --print_out --old --fine_tune_dict position_learner final_pos_predictor"

# rel1_batch_heuristic_search + ConsistentREL position
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_batch_heuristic_search_ConsistentREL --load_from rel1_batch_heuristic_search --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 1 0 0 --pos_pred_type 11 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --pos_valid_use pred --pos_train_use oracle --pos_enc_all --print_out --old --fine_tune_dict position_learner final_pos_predictor --pos_index_type quick"

# rel1_batch_heuristic_search + QuickSort position
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_batch_heuristic_search_QuickSort3 --load_from rel1_batch_heuristic_search --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 1 0 0 --pos_pred_type 10 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --pos_valid_use pred --pos_train_use oracle --pos_enc_all --print_out --old --fine_tune_dict position_learner final_pos_predictor --remove_last_layer_supervision --pos_recur_num 3 --batch_size 1024"

# rel1_batch_heuristic_search + Pos12
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_batch_heuristic_search_Pos12 --load_from rel1_batch_heuristic_search --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 1 0 0 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --pos_valid_use pred --pos_train_use oracle --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --batch_size 1024"

# rel1_shaw_heuristic_search + Pos12
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_shaw_heuristic_search_fix_Pos12 --load_from rel1_shaw_heuristic_search_fix --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 1 0 0 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --pos_valid_use pred --pos_train_use oracle --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw"


# rel8_shaw_heuristic_search with pos loss + skip_gram + emb
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel8_shaw_emb_gram_40000Pos12 --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 8 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 1 0 0 --pos_pred_type 12 --pos_index_out --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 0.1 --pos_init --keep_grad_for_pos_pred --keep_grad_for_pos_match --content_scale 0.2 --layer_bow_loss --layer_weight 0 0 0 --content_loss_type emb skip_gram pred --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 4 0 0 --state_share_output --pos_map_select f_double --final_pos_map_select f_double --print_out --pos_attn_type shaw --pos_start_epoch 40000"

===================================jointly proc and final predictor learning ++++++++++++++++++++++++++
# rel4_shaw_heuristic_search + Pos12 + Pos12
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_heuristic_search_Pos12_final_pos12 --load_from rel4_shaw_heuristic_search --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --proc_pos_train_use oracle --final_pos_valid_use pred --final_pos_train_use oracle --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw"

# rel4_batch_heuristic_search + Pos11Iter + Pos12
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_batch_heuristic_search_Pos11Iter3_final_pos12 --load_from rel4_batch_heuristic_search --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 11 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --proc_pos_train_use oracle --final_pos_valid_use pred --final_pos_train_use oracle --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_recur_num 3"

# rel1_batch_heuristic_search + Pos11Iter + Pos12
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_batch_heuristic_search_Pos11Iter3_final_pos12 --load_from rel1_batch_heuristic_search --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 11 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --proc_pos_train_use oracle --final_pos_valid_use pred --final_pos_train_use oracle --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_recur_num 3"


# rel1_batch_heuristic_search + ConstrainREL + Pos12
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_batch_heuristic_search_ConstrainREL_final_pos12 --load_from rel1_batch_heuristic_search --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 11 0 0 12 --pos_pred_type 11 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --pos_valid_use pred --pos_train_use oracle --pos_enc_all --print_out --old  --fine_tune_dict pos_predictor_list --remove_last_layer_supervision"

# rel1_batch_heuristic_search + ConstrainREL + ConstrainREL
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_batch_heuristic_search_ConstrainREL_final_pos11 --load_from rel1_batch_heuristic_search --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 11 0 0 11 --pos_pred_type 11 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --pos_valid_use pred --pos_train_use oracle --pos_enc_all --print_out --old  --fine_tune_dict pos_predictor_list --remove_last_layer_supervision"


# pos11_rel1_batch_heuristic_search_judge
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "pos12_rel1_batch_judge1 --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --pos_index_out --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --pos_init --keep_grad_for_pos_pred --keep_grad_for_pos_match --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --pos_train_use pred --pos_valid_use pred --print_out --rel_pos_judge"

# rel1_shaw_heuristic_search_tune + Pos12 + Pos12
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_shaw_heuristic_search_fix_tune_Pos12_final_pos12 --load_from rel1_shaw_heuristic_search_fix --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --pos_valid_use pred --pos_train_use oracle --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw --pos_funetune_grad"


# rel1_shaw_heuristic_search + Pos12 + Pos12 origin
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_shaw_heuristic_search_fix_Pos12_final_pos12origin --load_from rel1_shaw_heuristic_search_fix --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw --pos_index_new_oracle"

# rel1_shaw_emb_gram + Pos12 + Pos12
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_shaw_emb_gram_Pos12_final_pos12 --load_from rel1_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw"

# rel1_shaw_emb_gram + Pos12 + Pos12 + origin
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel1_shaw_emb_gram_Pos12_final_pos12origin --load_from rel1_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 1 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw --pos_index_new_oracle"

# rel4_shaw_emb_gram + Pos12 + Pos12
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12_final_pos12 --load_from rel4_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw"

# rel4_shaw_emb_gram + Pos12 + Pos12 + origin
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12_final_pos12origin --load_from rel4_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw --pos_index_new_oracle"

# rel4_shaw_emb_gram + Pos12 Unify + Pos12
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12U_final_pos12 --load_from rel4_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --proc_pos_train_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw"

rel4_shaw_emb_gram + Pos12 + Pos12 + Iter1
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12_Pos12Iter1 --load_from rel4_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list iter_content_learner --pos_attn_type shaw --content_iter_layer --pos_iter_layer --iter_num 1 --keep_grad_for_pos_match --keep_grad_for_pos_pred"

rel4_shaw_emb_gram + Pos12 + Pos12 Origin + Iter1
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12_Pos12OriginIter1 --load_from rel4_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list iter_content_learner --pos_attn_type shaw --content_iter_layer --pos_iter_layer --iter_num 1 --keep_grad_for_pos_match --keep_grad_for_pos_pred --pos_index_new_oracle"

#rel4_shaw_emb_gram + Pos12 + Pos12 + Iter2
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12_Pos12OriginIter2 --load_from rel4_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list iter_content_learner --pos_attn_type shaw --content_iter_layer --pos_iter_layer --iter_num 2 --pos_index_new_oracle --keep_grad_for_pos_match --keep_grad_for_pos_pred"

#rel4_shaw_emb_gram + Pos12 + Pos12 Origin + Iter1 + IterPos
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12_Pos12OriginIter1_IterPos --load_from rel4_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list iter_content_learner --pos_attn_type shaw --content_iter_layer --pos_iter_layer --iter_num 1 --keep_grad_for_pos_match --keep_grad_for_pos_pred --pos_index_new_oracle --final_use_iter_pos"

# rel4_shaw_heuristic_search with pos_loss + skip_gram + emb
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_4gram_40000Pos12 --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 1 0 0 --pos_pred_type 12 --pos_index_out --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 0.1 --pos_init --keep_grad_for_pos_pred --keep_grad_for_pos_match --content_scale 0.1 --layer_bow_loss --layer_weight 0 0 0 --content_loss_type emb skip_gram pred --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 4 0 0 --state_share_output --pos_map_select e_double --print_out --pos_attn_type shaw --pos_start_epoch 40000"

# rel4_shaw_emb_4gram_40000Pos12 + Pos12 + Pos12
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_4gram_40000Pos12_Pos12_final_pos12 --load_from rel4_shaw_emb_4gram_40000Pos12 --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw"

# rel4_shaw_emb_4gram_40000Pos12 + Pos12 + Pos12 + origin
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_4gram_40000Pos12_Pos12_final_pos12origin --load_from rel4_shaw_emb_4gram_40000Pos12 --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw --pos_index_new_oracle"

# rel8_shaw_emb_gram + Pos12 + Pos12 + origin
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel8_shaw_emb_gram_Pos12_Pos12origin --load_from rel8_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 8 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw --pos_index_new_oracle"


# rel4_shaw_emb_gram + Pos13 + Pos12
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos13_Pos12 --load_from rel4_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 13 0 0 12 --pos_pred_type 13 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw --pos_index_new_oracle"

# rel4_shaw_emb_gram + Pos13 + Pos12 + Init
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos13_Pos12_Init --load_from rel4_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 13 0 0 12 --pos_pred_type 13 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw --pos_index_new_oracle --pos_init"

# rel4_shaw_emb_gram + Pos12 + Pos14
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12_Pos14 --load_from rel4_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 14 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw"

# rel4_shaw_emb_gram + Pos14 + Pos12
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos14_Pos12 --load_from rel4_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 14 0 0 12 --pos_pred_type 14 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw"

# rel4_shaw_emb_gram + Pos14 + Pos14 + Pos Init
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos14_Pos14 --load_from rel4_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 14 0 0 14 --pos_pred_type 14 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw"

# rel4_shaw_emb_gram + Pos14 + Pos14 + Pos Init
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos14_Pos14_Init --load_from rel4_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 14 0 0 14 --pos_pred_type 14 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw --pos_init"

===================================iterative predictor learning ++++++++++++++++++++++++++
#rel4_shaw_emb_gram + Itered Content
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_iter1Content --load_from rel4_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 0.0 --pos_predict_weight 1 0 0 1 --content_scale 0.1 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --pos_enc_all --print_out --old --fine_tune_dict iter_content_learner --pos_attn_type shaw --content_iter_layer --pos_iter_layer --iter_num 1 --keep_grad_for_pos_match --keep_grad_for_pos_pred"

#rel4_shaw_emb_gram + Pos12 + Pos12 + Iter1 + 20000 Pretrain
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12_Pos12_Prtn20000Iter1 --load_from rel4_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list iter_content_learner --pos_attn_type shaw --content_iter_layer --pos_iter_layer --iter_num 1 --keep_grad_for_pos_match --keep_grad_for_pos_pred --pos_start_epoch 20000"


# rel4_shaw_emb_gram_iter1Content + Pos12 + Pos12
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_iter1Content_Pos12_Pos12_Iter2 --load_from rel4_shaw_emb_gram_iter1Content --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --pos_attn_type shaw --content_iter_layer --pos_iter_layer --iter_num 2 --keep_grad_for_pos_match --keep_grad_for_pos_pred"


# rel4_shaw_emb_gram + Pos12 + Pos12 + origin + Iterative Content
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12_Pos12O_IterContent --load_from rel4_shaw_emb_gram_Pos12_final_pos12origin --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --proc_pos_train_use pred --final_pos_train_use pred --pos_enc_all --print_out --old --fine_tune_dict iter_content_learner --pos_attn_type shaw --pos_index_new_oracle --iter_num 1 --content_iter_layer"

# rel4_shaw_emb_gram + Pos12 + Pos12 + origin + Iterative Content + Predict-Proc + Oracle Final Pos
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12_Pos12O_IterContent2 --load_from rel4_shaw_emb_gram_Pos12_final_pos12origin --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --proc_pos_train_use pred --pos_enc_all --print_out --old --fine_tune_dict iter_content_learner --pos_attn_type shaw --pos_index_new_oracle --iter_num 1 --content_iter_layer --pos_iter_layer"

# rel4_shaw_emb_gram + Pos12 + Pos12 origin + Init
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12_Pos12O_Init --load_from rel4_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw --pos_index_new_oracle --pos_init"

# rel4_shaw_emb_gram_Pos12_Pos12O_IterContent2 + Pos Training Origin
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12_Pos12O_IterContent2_Pos12 --load_from rel4_shaw_emb_gram_Pos12_Pos12O_IterContent2 --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 0 0 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --proc_pos_train_use pred --final_pos_valid_use pred --final_pos_train_use oracle --iter_pos_valid_use pred --iter_pos_train_use oracle --pos_iter_new_oracle --pos_enc_all --print_out --old --fine_tune_dict iter_pos_learner --pos_attn_type shaw --pos_index_new_oracle --iter_num 1 --train_iter 1 --valid_iter 1 --content_iter_layer --pos_iter_layer"

# rel4_shaw_emb_gram + Pos12 + Pos12 + origin + Iterative Content + Predict-Proc + Predict Final Pos
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12_Pos12O_IterContent3 --load_from rel4_shaw_emb_gram_Pos12_final_pos12origin --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --proc_pos_train_use pred --final_pos_valid_use pred --final_pos_train_use pred --pos_enc_all --print_out --old --fine_tune_dict iter_content_learner --pos_attn_type shaw --pos_index_new_oracle --iter_num 1 --content_iter_layer --pos_iter_layer"

# rel4_shaw_emb_gram_Pos12_Pos12O_IterContent2 + Pos Training + new oracle
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12_Pos12O_IterContent2_Pos12N --load_from rel4_shaw_emb_gram_Pos12_Pos12O_IterContent2 --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 0 0 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --proc_pos_train_use pred --final_pos_valid_use pred --final_pos_train_use oracle --iter_pos_valid_use pred --iter_pos_train_use oracle --pos_iter_new_oracle --pos_enc_all --print_out --old --fine_tune_dict iter_pos_learner --pos_attn_type shaw --pos_index_new_oracle --iter_num 1 --train_iter 1 --valid_iter 1 --pos_iter_new_oracle --content_iter_layer --pos_iter_layer"

# rel4_shaw_emb_gram_Pos12_Pos12O_IterContent2 + Pos Trainin with predict position + new oracle
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12_Pos12O_IterContent2_Pos12N_unify --load_from rel4_shaw_emb_gram_Pos12_Pos12O_IterContent2 --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 0 0 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --proc_pos_train_use pred --final_pos_valid_use pred --final_pos_train_use pred --iter_pos_valid_use pred --iter_pos_train_use oracle --pos_iter_new_oracle --pos_enc_all --print_out --old --fine_tune_dict iter_pos_learner --pos_attn_type shaw --pos_index_new_oracle --iter_num 1 --train_iter 1 --valid_iter 1 --pos_iter_new_oracle --content_iter_layer --pos_iter_layer"

# rel4_shaw_emb_gram + Pos12 + Pos12 + origin + Iterative Content + Predict-Proc + New Oracle Final Pos
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12P_Pos12N_IterContent --load_from rel4_shaw_emb_gram_Pos12_final_pos12origin --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --proc_pos_train_use pred --pos_enc_all --print_out --old --fine_tune_dict iter_content_learner --pos_attn_type shaw --iter_num 1 --content_iter_layer --pos_iter_layer"

# rel4_shaw_emb_gram + Pos12 + Pos12 Unify
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12_Pos12O_unify --load_from rel4_shaw_emb_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --proc_pos_train_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw --pos_index_new_oracle"

# rel4_shaw_emb_gram + Pos12 + Pos12 + origin + Iterative Content + Predict-Proc + Predict Final Pos + res_input
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_Pos12_Pos12O_IterContent4 --load_from rel4_shaw_emb_gram_Pos12_final_pos12origin --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --proc_pos_train_use pred --final_pos_valid_use pred --final_pos_train_use pred --pos_enc_all --print_out --old --fine_tune_dict iter_content_learner --pos_attn_type shaw --pos_index_new_oracle --iter_num 1 --content_iter_layer --pos_iter_layer"

# rel4_shaw_heuristic_search + state skip_gram + match max + output skip gram
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_out_gram --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 1 0 0 --pos_pred_type 12 --pos_index_out --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 0 --pos_init --keep_grad_for_pos_pred --keep_grad_for_pos_match --content_scale 0.1 --layer_bow_loss --layer_weight 0 0 0 --content_loss_type emb skip_gram pred --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 4 0 0 --state_share_output --pos_map_select e_double --print_out --pos_attn_type shaw --output_with_skip_gram"

# rel4_shaw_heuristic_search + state skip_gram + match max + output skip gram w/ fixed double match
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_out_gram_fixed_match --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 1 0 0 --pos_pred_type 12 --pos_index_out --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 0 --pos_init --keep_grad_for_pos_pred --keep_grad_for_pos_match --content_scale 0.1 --layer_bow_loss --layer_weight 0 0 0 --content_loss_type emb skip_gram pred --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 4 0 0 --state_share_output --pos_map_select f_double --final_pos_map_select f_double --print_out --pos_attn_type shaw --output_with_skip_gram"

# rel4_shaw_heuristic_search + state skip_gram + match max + output skip gram w/ fixed double match + layer bow loss
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_out_gram_fixed_match_bow --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 1 0 0 --pos_pred_type 12 --pos_index_out --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 0 --pos_init --keep_grad_for_pos_pred --keep_grad_for_pos_match --content_scale 0.1 --layer_bow_loss --layer_weight 1 1 1 --content_loss_type emb skip_gram pred --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 4 0 0 --state_share_output --pos_map_select f_double --final_pos_map_select f_double --print_out --pos_attn_type shaw --output_with_skip_gram"

# rel4_shaw_emb_gram_out_gram_fixed_match + Pos12 + Pos12 + origin
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_out_gram_fixed_match_Pos12_Pos12O --load_from rel4_shaw_emb_gram_out_gram_fixed_match --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select f_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw --pos_index_new_oracle"

# rel4_shaw_emb_gram_out_gram_fixed_match + Pos12 + Pos12 + new oracle
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_out_gram_fixed_match_Pos12_Pos12N --load_from rel4_shaw_emb_gram_out_gram_fixed_match --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select f_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw"

# rel4_shaw_emb_gram_out_gram_not_share + Pos12 + Pos12 + origin
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_out_gram_not_share_Pos12_Pos12O --load_from rel4_shaw_emb_gram_out_gram_not_share --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select e_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw --pos_index_new_oracle"

# rel4_shaw_emb_gram_out_gram_fixed_match_bow + Pos12 + Pos12 + origin
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_out_gram_fixed_match_bow_Pos12_Pos12O --load_from rel4_shaw_emb_gram_out_gram_fixed_match_bow --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select f_double --proc_pos_valid_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw --pos_index_new_oracle"

#===================================proc predicted oracle analysis ++++++++++++++++++++++++++

# rel4_shaw_emb_gram_out_gram_fixed_match + Pos12 Proc Oracle
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_out_gram_fixed_match_Pos12_Proc_Oracle --load_from rel4_shaw_emb_gram_out_gram_fixed_match --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 0 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select f_double --proc_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw"

# rel4_shaw_emb_gram_out_gram_fixed_match + Pos12 Iter 2 Proc Oracle
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_out_gram_fixed_match_Pos12_Iter2_Proc_Oracle --load_from rel4_shaw_emb_gram_out_gram_fixed_match --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 12 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0.5 0 0 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select f_double --proc_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw"

# rel4_shaw_emb_gram_out_gram_fixed_match + Pos12 Proc Oracle + LSTM
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_out_gram_fixed_match_Pos12_Proc_Oracle_LSTM --load_from rel4_shaw_emb_gram_out_gram_fixed_match --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 0 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select f_double --proc_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw --pos_enc_cls rnn"

# rel4_shaw_emb_gram_out_gram_fixed_match + Pos12 Proc Oracle + LSTM-MULTI
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_out_gram_fixed_match_Pos12_Proc_Oracle_LSTM-MULTI --load_from rel4_shaw_emb_gram_out_gram_fixed_match --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 0 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select f_double --proc_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw --pos_enc_cls rnn-multi"

# rel4_shaw_emb_gram_out_gram_fixed_match_bow + Pos12 Proc Oracle + LSTM
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_out_gram_fixed_match_bow_Pos12_Proc_Oracle_LSTM --load_from rel4_shaw_emb_gram_out_gram_fixed_match_bow --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 0 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select f_double --proc_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw --pos_enc_cls rnn --pos_index_norm"

# rel4_shaw_emb_gram_out_gram_fixed_match + Pos12 Proc Fixed Oracle
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_out_gram_fixed_match_Pos12_Proc_Fixed_Oracle --load_from rel4_shaw_emb_gram_out_gram_fixed_match --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 1 0 0 0 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select f_double --proc_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict pos_predictor_list --remove_last_layer_supervision --pos_attn_type shaw --final_pos_map_select f_double --pos_index_norm"

# ===================================final predicted oracle learning ++++++++++++++++++++++++++
# load pretrained proc position module and the content learner, train a oracle rank position, convert it to oracle output.

# rel4_shaw_emb_gram_out_gram_fixed_match_bow_Pos12P_Pos12: rel4_shaw_emb_gram_out_gram_fixed_match_bow_Pos12_Proc_Oracle_LSTM + Predicted Final Pos
sh debug.sh BYTETRANS iwslt-deen PositionalFasterTransformer "rel4_shaw_emb_gram_out_gram_fixed_match_bow_Pos12P_Pos12 --load_from rel4_shaw_emb_gram_out_gram_fixed_match_bow_Pos12_Proc_Oracle_LSTM --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --d_model 400 --d_hidden 800 --n_heads 4 --n_layers 3 --warmup 746 --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 12 0 0 12 --pos_pred_type 12 --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_predict_weight 0 0 0 1 --content_scale 0.0 --layer_bow_loss --layer_weight 0 1 1 --content_loss_type emb skip_gram pred --pos_index_out --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 3 0 0 --state_share_output --pos_map_select f_double --proc_pos_valid_use pred --proc_pos_train_use pred --final_pos_valid_use pred --pos_enc_all --print_out --old --fine_tune_dict final_pos_learner --remove_last_layer_supervision --pos_attn_type shaw --pos_enc_cls rnn --pos_index_norm"

# for wmt14-enro
sh debug.sh BYTETRANS wmt16-enro PositionalFasterTransformer "rel4_default_params_pos12_Oracle --load_from rel4_defult_params_pos12 --decoder_input_how interpolate --decoder_query_select hidden --use_distillation --pos_match_norm --ar_supervised --max_rel_len 4 --load_vocab --share_vocab --share_embed --params transformer-base --ffw_block highway --share_pos_repr --share_pos_pred --pos_n_layers 2 --pos_predict_layer 1 0 0 0 0 1 --pos_pred_type 12 --pos_index_out --valid_with_teacher --pos_order_scale 0 --pos_predict_scale 1.0 --pos_init --keep_grad_for_pos_pred --keep_grad_for_pos_match --content_scale 0.0 --layer_bow_loss --layer_weight 1 1 1 --content_loss_type emb skip_gram pred --pos_index_state --state_bow_loss --state_weight 1 0 0 --state_window_size 4 0 0 --state_share_output --pos_map_select f_double --print_out --pos_attn_type shaw --output_with_skip_gram --lr_schedule transformer --data_dir /mnt/cephfs_wj/common/lab/baoyu.nlp/origin_data --vocab_size 40000 --fine_tune_dict pos_predictor_list --final_pos_map_select f_double --remove_last_layer_supervision --pos_enc_cls rnn --pos_index_norm --proc_pos_valid_use pred"